services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: example
    expose:
      - 5432


  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - spring-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  spring-postgres:
